Reporting_malfunction_system/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^tinymce/', include('tinymce.urls')),
    re_path(r'^',include('web.urls',)),
    re_path(r'^backend/',include('backend.urls',namespace='backend')),
]

backend/urls.py
# -*- coding: utf-8 -*-

"""
@Datetime: 2018/9/30
@Author: Zhang Yafei
"""
from django.conf.urls import url
from backend.views import user,trouble

app_name = 'backend'

urlpatterns = [
    url(r'^index.html$', user.index, name='backend_index'),
    url(r'^article-(?P<type_id>\d+)-(?P<tag_id>\d+).html$', user.article, name='backend_article'),
    url(r'^edit_article-(\d+).html$', user.edit_article, name='backend_edit_article'),
    url(r'^add_article.html$', user.add_article, name='backend_add_article'),
    url(r'^del_article.html$', user.del_artcile, name='backend_del_article'),
    url(r'article_classification.html', user.article_classification, name='article_classification'),
    url(r'^add_classification$', user.add_classification, name='add_classification'),
    url(r'^del_classification$', user.del_classification, name='del_classification'),
    url(r'^edit_classification$', user.edit_classification, name='edit_classification'),
    url(r'^article_tag.html', user.article_tag, name='article_tag'),
    url(r'^add_tag$', user.add_tag, name='add_tag'),
    url(r'^edit_tag$', user.edit_tag, name='edit_tag'),
    url(r'^del_tag$', user.del_tag, name='del_tag'),
    url(r'^article_images$', user.article_images, name='article_images'),

    #一般用户：提交报障单，查看，修改（未处理状态），评分（处理完成，未评分）
    url(r'^trouble-list$',trouble.trouble_list,name='trouble-list'),
    url(r'^trouble-create$',trouble.trouble_create,name='trouble_create'),
    url(r'^trouble-edit-(\d+)$',trouble.trouble_edit,name='trouble_edit'),
    url(r'^trouble-del$',trouble.trouble_del,name='trouble_del'),
    url(r'^trouble-detail-(\d+)$',trouble.trouble_detail,name='trouble_detail'),
    url(r'^trouble-evalute$',trouble.trouble_evalute,name='trouble_evalute'),

    url(r'^trouble-kill-list$',trouble.trouble_kill_list,name='trouble_kill_list'),
    url(r'^trouble-kill-(\d+)$',trouble.trouble_kill,name='trouble_kill'),
    url(r'^trouble-kill-del$',trouble.trouble_kill_del,name='trouble_kill_del'),

    url(r'^trouble-temp-list$',trouble.trouble_temp_list,name='trouble_temp_list'),
    url(r'^trouble-temp-create$',trouble.trouble_temp_create,name='trouble_temp_create'),
    url(r'^trouble-temp-edit-(\d+)$',trouble.trouble_temp_edit,name='trouble_temp_edit'),
    url(r'^trouble-temp-del$',trouble.trouble_temp_del,name='trouble_temp_del'),

    url(r'^trouble-report$',trouble.trouble_report,name='trouble_report'),
    url(r'^trouble-json-report$',trouble.trouble_json_report,name='trouble_json_report'),

    url(r'^personal-view.html$',user.personal_view,name='personal_view'),
    url(r'^personal-update.html$',user.personal_update,name='personal_update'),
    url(r'^personal-update-pwd.html$',user.personal_update_pwd,name='personal_update_pwd'),
    url(r'^personal-blog.html$',user.personal_blog,name='personal_blog'),
    url(r'^personal-update-blog.html$',user.personal_update_blog,name='personal_update_blog'),
    url(r'^my_image$',user.my_image,name='my_image'),

    url(r'^user-list$',user.user_list,name='user_list'),
    url(r'^del-user$',user.del_user,name='del_user'),
    url(r'^add-user$',user.add_user,name='add_user'),
    url(r'^edit-user$',user.edit_user,name='edit_user'),
]

web/urls.py
# -*- coding: utf-8 -*-

"""
@Datetime: 2018/9/25
@Author: Zhang Yafei
"""
from django.conf.urls import url
from web.views import home,account

urlpatterns = [
    url(r'^$', home.index),
    url(r'^all/(?P<article_type_id>\d+).html$', home.index, name='index'),
    url(r'^login.html$',account.login,name='login'),
    url(r'^register.html$',account.register,name='register'),
    url(r'^logout.html$',account.logout,name='logout'),
    url(r'^check_code.html',account.check_code,name='check_code'),
    url(r'^get_check_code',account.get_check_code,name='get_check_code'),
    url(r'^comment_images.html$',home.comment_images,name='comment_images'),
    url(r'^submitComment$',home.submitComment,name='submitComment'),
    url(r'^del_comment$',home.del_comment,name='del_comment'),
    url(r'^article_up_or_down',home.article_up_or_down,name='article_up_or_down'),
    url(r'^(?P<blog_site>\w+)/(?P<condition>((date)|(types)|(tag)))/(?P<value>\w+-*\w*).html$',home.filter,name='filter'),
    url(r'^(?P<blog_site>\w+).html$',home.home,name='home'),
    url(r'^(\w+)/(\d+).html$',home.article_detail,name='article_detail'),
]

templates/include/footer.html
<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
            <span>|</span>
            <a id="map">网站地图</a>
		</div>
    <p style="margin-top: 10px;"><a style="color: #fff;" href="/">老子的技术论坛</a></p>
		<p>电话：157****7116  &nbsp;&nbsp;  晋ICP备*******8号</p>
	</div>

templates/include/header.html
<nav class="navbar navbar-inverse navbar-default">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" style="font-size: 20px;" href="/">老子的技术论坛</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% if not article_type_id %}
                    <li class="active"><a href="/">全部</a></li>
                {% else %}
                    <li><a href="/">全部</a></li>
                {% endif %}
                {% for item in article_type_list %}
                    {% if article_type_id == item.0 %}
                        <li class="active"><a href="/all/{{ item.0 }}.html">{{ item.1 }}</a></li>
                    {% else %}
                        <li><a href="/all/{{ item.0 }}.html">{{ item.1 }}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.session.user_info %}
                    <li>
                        <a href="{% url 'backend:backend_index' %}">{{ request.session.user_info.nickname }}</a>
                    </li>
                    {% if request.session.user_info.blog__suffix %}
                    <li>
                        <a href="{% url 'home' blog_site=request.session.user_info.blog__suffix %}">我的博客</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'backend:backend_index' %}">管理</a>
                    </li>
                    {% endif %}
                    <li>
                        <a href="{% url 'logout' %}">注销</a>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}">登录</a></li>
                    <li><a href="{% url 'register' %}">注册</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/include/map.html
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>网站地图</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
<style type="text/css">
html,body{
    width:100%;
    height:100%;
}
*{
    margin:0px;
    padding:0px;
}
body {
    font: 12px/16px Verdana, Helvetica, Arial, sans-serif;
}
#container{
    margin: 100px auto;
    width:600px;
    height:600px;
    border: 1px solid blue;
}
</style>
<script charset="utf-8" src="https://map.qq.com/api/js?v=2.exp&key=RKTBZ-HQOKX-HW34M-TAKPQ-HGXA7-4XF7F"></script>
<script>
window.onload = function(){
    function init() {
        // 创建地图
        var map = new qq.maps.Map(document.getElementById("container"), {
            center: new qq.maps.LatLng(37.850030,112.554490),      // 地图的中心地理坐标
            zoom: 15,     // 地图缩放级别
            mapStyleId: 'style1'  // 该key绑定的style1对应于经典地图样式，若未绑定将弹出无权限提示窗
        });
    }
    //调用初始化函数
    init();
}
</script>
</head>
<body>
<!--   定义地图显示容器   -->
<div id="container"></div>
</body>
</html>