Reporting_malfunction_system/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^tinymce/', include('tinymce.urls')),
    re_path(r'^',include('web.urls',)),
    re_path(r'^backend/',include('backend.urls',namespace='backend')),
]

backend/urls.py
# -*- coding: utf-8 -*-

"""
@Datetime: 2018/9/30
@Author: Zhang Yafei
"""
from django.conf.urls import url
from backend.views import user,trouble

app_name = 'backend'

urlpatterns = [
    url(r'^index.html$', user.index, name='backend_index'),
    url(r'^article-(?P<type_id>\d+)-(?P<tag_id>\d+).html$', user.article, name='backend_article'),
    url(r'^edit_article-(\d+).html$', user.edit_article, name='backend_edit_article'),
    url(r'^add_article.html$', user.add_article, name='backend_add_article'),
    url(r'^del_article.html$', user.del_artcile, name='backend_del_article'),
    url(r'article_classification.html', user.article_classification, name='article_classification'),
    url(r'^add_classification$', user.add_classification, name='add_classification'),
    url(r'^del_classification$', user.del_classification, name='del_classification'),
    url(r'^edit_classification$', user.edit_classification, name='edit_classification'),
    url(r'^article_tag.html', user.article_tag, name='article_tag'),
    url(r'^add_tag$', user.add_tag, name='add_tag'),
    url(r'^edit_tag$', user.edit_tag, name='edit_tag'),
    url(r'^del_tag$', user.del_tag, name='del_tag'),
    url(r'^article_images$', user.article_images, name='article_images'),

    #一般用户：提交报障单，查看，修改（未处理状态），评分（处理完成，未评分）
    url(r'^trouble-list$',trouble.trouble_list,name='trouble-list'),
    url(r'^trouble-create$',trouble.trouble_create,name='trouble_create'),
    url(r'^trouble-edit-(\d+)$',trouble.trouble_edit,name='trouble_edit'),
    url(r'^trouble-del$',trouble.trouble_del,name='trouble_del'),
    url(r'^trouble-detail-(\d+)$',trouble.trouble_detail,name='trouble_detail'),
    url(r'^trouble-evalute$',trouble.trouble_evalute,name='trouble_evalute'),

    url(r'^trouble-kill-list$',trouble.trouble_kill_list,name='trouble_kill_list'),
    url(r'^trouble-kill-(\d+)$',trouble.trouble_kill,name='trouble_kill'),
    url(r'^trouble-kill-del$',trouble.trouble_kill_del,name='trouble_kill_del'),

    url(r'^trouble-temp-list$',trouble.trouble_temp_list,name='trouble_temp_list'),
    url(r'^trouble-temp-create$',trouble.trouble_temp_create,name='trouble_temp_create'),
    url(r'^trouble-temp-edit-(\d+)$',trouble.trouble_temp_edit,name='trouble_temp_edit'),
    url(r'^trouble-temp-del$',trouble.trouble_temp_del,name='trouble_temp_del'),

    url(r'^trouble-report$',trouble.trouble_report,name='trouble_report'),
    url(r'^trouble-json-report$',trouble.trouble_json_report,name='trouble_json_report'),

    url(r'^personal-view.html$',user.personal_view,name='personal_view'),
    url(r'^personal-update.html$',user.personal_update,name='personal_update'),
    url(r'^personal-update-pwd.html$',user.personal_update_pwd,name='personal_update_pwd'),
    url(r'^personal-blog.html$',user.personal_blog,name='personal_blog'),
    url(r'^personal-update-blog.html$',user.personal_update_blog,name='personal_update_blog'),
    url(r'^my_image$',user.my_image,name='my_image'),

    url(r'^user-list$',user.user_list,name='user_list'),
    url(r'^del-user$',user.del_user,name='del_user'),
    url(r'^add-user$',user.add_user,name='add_user'),
    url(r'^edit-user$',user.edit_user,name='edit_user'),
]

web/urls.py
# -*- coding: utf-8 -*-

"""
@Datetime: 2018/9/25
@Author: Zhang Yafei
"""
from django.conf.urls import url
from web.views import home,account

urlpatterns = [
    url(r'^$', home.index),
    url(r'^all/(?P<article_type_id>\d+).html$', home.index, name='index'),
    url(r'^login.html$',account.login,name='login'),
    url(r'^register.html$',account.register,name='register'),
    url(r'^logout.html$',account.logout,name='logout'),
    url(r'^check_code.html',account.check_code,name='check_code'),
    url(r'^get_check_code',account.get_check_code,name='get_check_code'),
    url(r'^comment_images.html$',home.comment_images,name='comment_images'),
    url(r'^submitComment$',home.submitComment,name='submitComment'),
    url(r'^del_comment$',home.del_comment,name='del_comment'),
    url(r'^article_up_or_down',home.article_up_or_down,name='article_up_or_down'),
    url(r'^(?P<blog_site>\w+)/(?P<condition>((date)|(types)|(tag)))/(?P<value>\w+-*\w*).html$',home.filter,name='filter'),
    url(r'^(?P<blog_site>\w+).html$',home.home,name='home'),
    url(r'^(\w+)/(\d+).html$',home.article_detail,name='article_detail'),
]

repository/models.py
from django.db import models
from tinymce.models import HTMLField


class UserInfo(models.Model):
    """
    用户信息表
    """
    username = models.CharField(max_length=32,verbose_name='用户名',unique=True)
    pwd = models.CharField(max_length=16,verbose_name='密码')
    nickname = models.CharField(max_length=32,verbose_name='昵称',unique=True)
    email = models.EmailField(verbose_name='邮箱',unique=True)
    img = models.ImageField(verbose_name='图片',upload_to='static/upload/photo')
    create_time = models.DateTimeField(verbose_name='创建时间',auto_now_add=True)

    fans = models.ManyToManyField(verbose_name='粉丝们',to='UserInfo',through='Fans',related_name='f',through_fields=('user','fan'))

    class Meta:
        verbose_name_plural = '用户信息'

    def __str__(self):
        return self.username


class Blog(models.Model):
    """
    个人博客信息表
    """
    suffix = models.CharField(max_length=32,verbose_name='主站名称',unique=True)
    theme = models.CharField(max_length=32,verbose_name='博客主题',default='warm')
    title = models.CharField(max_length=32,verbose_name='个人博客标题')
    summary = models.CharField(max_length=32,verbose_name='博客简介')

    user = models.OneToOneField('UserInfo',on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '博客表'

    def __str__(self):
        return self.suffix


class Fans(models.Model):
    """
    粉丝表
    """
    user = models.ForeignKey('UserInfo',related_name='users',on_delete=models.CASCADE)
    fan = models.ForeignKey('UserInfo',on_delete=models.CASCADE,related_name='fan')

    class Meta:
        verbose_name_plural = '互粉表'


class Classification(models.Model):
    """
    个人博客文章分类表
    """
    title = models.CharField(max_length=32,verbose_name='分类标题')
    blog = models.ForeignKey('Blog',verbose_name='所属博客',related_name='classification',on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '分类'

    def __str__(self):
        return self.title


class Tags(models.Model):
    """
    个人博客文章标签表
    """
    title = models.CharField(max_length=32)
    blog = models.ForeignKey('Blog',on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '标签'

    def __str__(self):
        return self.title


class Article(models.Model):
    """
    文章信息表
    """
    title = models.CharField(max_length=32,verbose_name='标题')
    summary = models.CharField(max_length=128,verbose_name='概述')
    detail = HTMLField(verbose_name='正文')
    create_time = models.DateTimeField(verbose_name='创建时间',auto_now_add=True)
    read_count = models.IntegerField(default=0,verbose_name='阅读次数')
    up_count = models.IntegerField(default=0,verbose_name='点赞次数')
    down_count = models.IntegerField(default=0,verbose_name='踩次数')
    comment_count = models.IntegerField(default=0,verbose_name='评论次数')
    img = models.ImageField(verbose_name='文章封面',upload_to='static/upload/artcle',null=True)
    blog = models.ForeignKey(to='Blog',verbose_name='所属博客',on_delete=models.CASCADE,related_name='article')
    article_classification = models.ForeignKey('Classification',verbose_name='个人博客文章分类',on_delete=models.SET_NULL,null=True,related_name='classification')
    publish_choices = (
        (0,'未发布'),
        (1,'已发布'),
    )
    publish = models.IntegerField(choices=publish_choices,default=0)

    type_choices = [(1,'Python全栈'),(2,'大数据'),(3,'WEB开发'),(4,'前端与移动开发'),(5,'运维'),(6,'数据库')]

    article_type_id = models.IntegerField(choices=type_choices,default=None,verbose_name='文章类型')

    tags = models.ManyToManyField(to='Tags',through='Ariticle_Tags',through_fields=('article','tag'))

    class Meta:
        verbose_name_plural = '文章'

    def __str__(self):
        return self.title


class Ariticle_Tags(models.Model):
    """
    文章标签表
    """
    article = models.ForeignKey('Article',on_delete=models.CASCADE)
    tag = models.ForeignKey('Tags',on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '文章标签'


class Article_like_dislike(models.Model):
    """
    文章点赞表
    """
    article = models.ForeignKey('Article',on_delete=models.CASCADE,related_name='likes')
    user = models.ForeignKey('UserInfo',on_delete=models.CASCADE,related_name='likes')
    like = models.BooleanField(verbose_name='是否赞')

    #ManyToManyField字段默认生成联合唯一
    class Meta:
        verbose_name_plural = '文章点赞或踩'
        unique_together = [('article','user')]


class Comment(models.Model):
    """
    评论表
    """
    content = models.CharField(max_length=128,verbose_name='评论')
    article = models.ForeignKey('Article',on_delete=models.CASCADE,verbose_name='评论文章',related_name='comment')
    comment_user = models.ForeignKey('UserInfo',on_delete=models.CASCADE,verbose_name='评论者')
    comment_time = models.DateTimeField(auto_now_add=True,verbose_name='评论时间')
    parent_id = models.ForeignKey(to='self',on_delete=models.CASCADE,blank=True,null=True)

    class Meta:
        verbose_name_plural = '评论表'


class Trouble(models.Model):
    """
    报障单
    """
    title = models.CharField(max_length=32)
    detail = models.TextField()
    user = models.ForeignKey(to='UserInfo',related_name='u',on_delete=models.CASCADE)
    # ctime = models.CharField(max_length=32)
    ctime = models.DateTimeField()
    status_choices=(
        (1,'未处理'),
        (2,'处理中'),
        (3,'已处理'),
    )
    status = models.IntegerField(choices=status_choices,default=1)

    processor = models.ForeignKey(UserInfo,related_name='p',null=True,blank=True,on_delete=models.SET_NULL)
    solution = models.TextField(null=True,blank=True)
    ptime = models.DateTimeField(null=True,blank=True)

    evaluate_choices = (
        (1, '不满意'),
        (2, '一般'),
        (3, '活很好'),
    )
    evaluate = models.IntegerField(choices=evaluate_choices,null=True,blank=True)

    class Meta:
        verbose_name_plural = '报障单'

    def __str__(self):
        return self.title


class TroubleTemplate(models.Model):
    """
    报障单模板表
    """
    title = models.CharField(max_length=32)
    context = models.TextField()
    user = models.ForeignKey('UserInfo',on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '报障单模板'

    def __str__(self):
        return self.title


class Role(models.Model):
    """
    角色表
    """
    name = models.CharField(max_length=32)

    class Meta:
        verbose_name_plural='角色表'

    def __str__(self):
        return self.name


class UserinfoToRole(models.Model):
    """
    用户和角色之间是多对多关系
    """
    user = models.ForeignKey(to='UserInfo',on_delete=models.CASCADE)
    role = models.ForeignKey(to='Role',on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural='用户分配角色表'

    def __str__(self):
        return '{}-{}'.format(self.user.username,self.role.name)


class Action(models.Model):
    """
    每个url地址中的具体操作权限
    ?get        查询
    ?post       增
    ?put        改
    ?delete     删
    """
    caption = models.CharField(max_length=32)
    code = models.CharField(max_length=32)

    class Meta:
        verbose_name_plural='操作表'

    def __str__(self):
        return self.caption


class Permission(models.Model):
    """
    url地址权限
    """

    caption = models.CharField(max_length=32)
    url = models.CharField(max_length=128)
    menu = models.ForeignKey('Menu',null=True,blank=True,on_delete=models.SET_NULL)

    class Meta:
        verbose_name_plural='URL表'

    def __str__(self):
        return '{}-{}'.format(self.caption,self.url)


class PermissionToAction(models.Model):
    """
    url权限与具体操作权限多对多关系
    """
    permission = models.ForeignKey(to='Permission',on_delete=models.CASCADE)
    action = models.ForeignKey(to='Action',on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural='权限表'

    def __str__(self):
        return '{}-{}:{}?t={}'.format(self.permission.caption,self.action.caption,self.permission.url,self.action.code)


class RoleToPremissionToAction(models.Model):
    """
    角色与权限是多对多关系
    """
    role = models.ForeignKey(to='Role',on_delete=models.CASCADE)
    p2a = models.ForeignKey(to='PermissionToAction',on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural='角色分配权限'

    def __str__(self):
        return '{}-{}'.format(self.role.name,self.p2a)


class Menu(models.Model):
    """
    1   菜单1     null
    2   菜单2     null
    3   菜单3     null
    4   菜单1.1    1
    5   菜单1.2    1
    6   菜单1.2.1  4
    无最后一层
    """
    caption = models.CharField(max_length=32)
    parent = models.ForeignKey('self',related_name='p',null=True,blank=True,on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural='菜单表'

    def __str__(self):
        return self.caption

templates/backend_edit_article.html
{% extends 'backend_loyout.html' %}
{% block title %}编辑文章{% endblock %}
{% block css  %}
    <style>
        .edit-article-title{
            width: 100%;
            height: 48px;
            background-color: #dddddd;
            list-style: none;
            line-height: 48px;
        }
        .edit-article-title li{
            display: inline-block;
            margin-right: 5px;
        }
        .article-form{
            padding: 0 30px 50px;
        }
        .kind-content{
            width: 100%;
            min-height: 500px;
        }
    </style>
{% endblock %}

{% block content %}
    <ul class="edit-article-title">
        <li style="color: #2aabd2">文章管理</li>
        <li><i class="fa fa-arrow-right" style="margin-right: 5px;"></i>编辑文章</li>
    </ul>
    <div class="article-form">
        <form action="{% url 'backend:backend_edit_article' id %}" method="post" novalidate enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.title.id_for_label }}">标题 <span>{{ form.title.errors.0 }}</span></label>
                {{ form.title }}
            </div>
            <div class="form-group">
                <label for="summary">简介 <span>{{ form.summary.errors.0 }}</span></label>
                {{ form.summary }}
            </div>
            <div class="form-group">
                <label>内容 <span>{{ form.detail.errors.0 }}</span></label>
                {{ form.detail }}
            </div>
            <div class="form-group">
                <label>文章封面 <span>{{ form.img.errors.0 }}</span></label>
                {{ form.img }}
            </div>
            <div class="form-group">
                <label>类型 <span>{{ form.article_type_id.errors.0 }}</span></label>
                <div>
                    {{ form.article_type_id }}
                </div>

            </div>
            <div class="form-group">
                <label>分类 <span>{{ form.article_classification_id.errors.0 }}</span></label>

                <div>
                    {{ form.article_classification_id }}
                </div>
            </div>
            <div class="form-group">
                <label>标签 <span>{{ form.tags.errors.0 }}</span></label>
                <div>
                    {{ form.tags }}
                </div>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" name="publish" value="发 布">
                <input type="submit" class="btn btn-success" name="save" value="保 存" style="float: right;margin-right: 100px;">
            </div>
        </form>
    </div>
{% endblock %}

{% block js %}
    <script charset="utf-8" src="/static/plugins/kingeditor/kindeditor-all-min.js"></script>
    <script charset="utf-8" src="/static/plugins/kingeditor/lang/zh-CN.js"></script>
    <script>
        KindEditor.ready(function (K) {
            var editor = K.create('textarea[name="detail"]', {
                resizeType: 1,
                allowImageUpload: true,
                uploadJson: '{% url "backend:article_images" %}',
                filePostName: 'images',
            });
        });
    </script>
{% endblock %}

templates/backend_personal_blog.html
{% extends 'backend_loyout.html' %}

{% block css %}
    <style>
        .personal-title {
            width: 100%;
            height: 48px;
            list-style: none;
            line-height: 48px;
        }

        .personal-title li {
            display: inline-block;
            margin-right: 5px;
        }

        .personal {
            width: 80%;
            margin: 0 auto;
            padding: 50px;
        }
        .form-control{
            width: 500px;
            float: right;
        }
        .fm {
            width: 60%;
            margin: 10px auto;
        }
        .form-group{
            float: left;
        }
        .submit-row{
            float: right;
        }
        .blog-manage .item-content{
            display: block;
        }
    </style>
{% endblock %}

{% block content %}
    <ul class="personal-title">
        <li style="color: #2aabd2">个人管理</li>
        <li><i class="fa fa-arrow-right" style="margin-right: 5px;"></i>博客管理</li>
    </ul>
    <div class="personal">
        <form class="fm" method="post" action="{% url 'backend:personal_update_pwd' %}" novalidate>
            {% csrf_token %}
            <div class="form-group">
                <label for="username">个人博客站点前缀</label>
                <input type="text" class="form-control" name="suffix" value="{{ blog.suffix }}" readonly>
            </div>
            <div class="form-group">
                <label for="theme">主题</label>
                <select name="theme" readonly>
                    <option readonly>{{ blog.theme }}</option>
                </select>
            </div>
            <div class="form-group">
                <label for="title">博客标题</label>
                <input type="text" class="form-control" name="title" value="{{ blog.title }}" readonly>
            </div>
            <div class="form-group">
                <label for="pwd">博客简介</label>
                <textarea rows="3" class="form-control" name="summary" readonly>{{ blog.summary }}</textarea>
             </div>
            <div class="submit-row">
                <a class="btn btn-primary" href="{% url 'backend:personal_update_blog' %}">
                    {% if blog %}去修改
                    {% else %}开通博客
                    {% endif %}
                </a>
            </div>
        </form>
    </div>
{% endblock %}

{% block js %}
{#        <script>#}
{#            $('.submit-btn').click(function () {#}
{#                $.ajax({#}
{#                    url:'{% url "backend:personal_update" %}',#}
{#                    type:'POST',#}
{#                    data:$('.fm').serialize(),#}
{#                    dataType:'JSON',#}
{#                    success:function (arg) {#}
{#                        console.log(arg);#}
{#                    }#}
{#                })#}
{#            })#}
{#        </script>#}
{% endblock %}

templates/backend_trouble_kill.html
{% extends 'backend_loyout.html' %}
{% block title %}创建文章{% endblock %}
{% block css %}
    <style>
        .add-article-title {
            width: 100%;
            height: 48px;
            list-style: none;
            line-height: 48px;
        }

        .add-article-title li {
            display: inline-block;
            margin-right: 5px;
        }

        .article-form {
            padding: 0px 30px;
        }
        .temp{
            float: right;
            margin-right: 50px;
        }
        #add-temp{
            margin-bottom: 6px;
        }
        .kind-editor {
            width: 100%;
            min-height: 600px;
        }
    </style>
{% endblock %}

{% block content %}
    <ul class="add-article-title">
        <li style="color: #2aabd2">报障管理</li>
        <li><i class="fa fa-arrow-right" style="margin-right: 5px;"></i>接单</li>
    </ul>
    <div class="article-form">
        <form action="{% url 'backend:trouble_kill' id %}" method="post" novalidate>
            {% csrf_token %}

            <div class="form-group">
                <label for="{{ form.title.id_for_label }}">标题 <span>{{ form.title.errors.0 }}</span></label>
                {{ form.title }}
            </div>
            <div class="temp">
                <select id="temp-select">
                    {% for row in temp %}
                        <option v="{{ row.context }}">{{ row.title }}</option>
                    {% endfor %}
                </select>
                <a id="add-temp"class="btn btn-success btn-xs" href="{% url 'backend:trouble_temp_list' %}"><i class="fa fa-plus"></i></a>
            </div>
            <div class="form-group">
                <label>解决方案 <span>{{ form.detail.errors.0 }}</span></label>
                {{ form.solution }}
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="提 交">
                <a class="btn btn-success" href="{% url 'backend:trouble_kill_list' %}" style="float: right;margin-right: 100px;">稍后处理</a>
            </div>
        </form>
    </div>
{% endblock %}

{% block js %}
    <script charset="utf-8" src="/static/plugins/kingeditor/kindeditor-all-min.js"></script>
    <script charset="utf-8" src="/static/plugins/kingeditor/lang/zh-CN.js"></script>
    <script>
        var editor = null;
        KindEditor.ready(function (K) {
            editor = K.create('#solution', {
                resizeType: 1,
                allowImageUpload: true,
                uploadJson: '{% url "backend:article_images" %}',
                filePostName: 'images',
            });
        });
        $('#temp-select').bind('change', function () {
            var index = this.selectedIndex;
            var v = this.value;
            var $ele = this.options[index];
            var content = $ele.getAttribute('v');
            //var index1 = $(this).get(0).selectedIndex;$(this)[0].selectedIndex
            //var v1 = $(this).val();
            //var content1 = $(this).find('option:selected').attr('v');
            //console.log(index,v,index1,v1);
            //console.log(content,content1);
            editor.html(content);
        })
    </script>
{% endblock %}

templates/backend_trouble_kill_list.html
{% extends 'backend_loyout.html' %}

{% block title %}后台管理-报障管理{% endblock %}
{% block css %}
    <style>
        .article-manage-title {
            width: 100%;
            height: 48px;
            line-height: 48px;
            list-style: none;
        }

        .article-manage-title li {
            display: inline-block;
            margin-right: 5px;
        }
        .condition a {
            display: inline-block;
            padding: 5px 8px;
            border: 1px solid #dddddd;
            text-decoration: none;
            margin-right: 10px;
        }
        .pager {
            float: right;
        }
    </style>
{% endblock %}
{% block content %}
    <ul class="article-manage-title">
        <li style="color: #2aabd2">报障管理</li>
        <li><i class="fa fa-arrow-right" style="margin-right: 5px;"></i>处理障单列表</li>
    </ul>
        <div class="clearfix"
             style="height: 36px;line-height: 35px;padding: 0 15px;border-top: 1px solid #dddddd;background-color: #f1f0f0">
            <i class="fa fa-table" aria-hidden="true"></i>
            报障单列表({{ result.count }}单)
        </div>
        <div style="padding-left: 20px;">
            <table id="tb" class="table table-bordered">
                <thead>
                <tr>
                    <th class="col-md-3">报障标题</th>
                    <th class="col-md-2">状态</th>
                    <th class="col-md-2">创建时间</th>
                    <th class="col-md-2">创建人</th>
                    <th class="col-md-3">操作</th>
                </tr>
                </thead>
                <tbody>
                {% for row in result %}
                    <tr nid="{{ row.id }}">
                        <td><a href="{% url 'backend:trouble_detail' row.id %}">{{ row.title }}</a></td>
                        <td>{{ row.get_status_display }}</td>
                        <td>{{ row.ctime }}</td>
                        <td>{{ row.user.nickname }}</td>
                        <td>
                            {% if row.status == 1 %}
                                <a href="{% url 'backend:trouble_kill' row.id %}" class="btn btn-success btn-xs">
                                <i class="fa fa-pencil"></i>
                                抢单
                            {% elif row.status == 2 %}
                                <a href="{% url 'backend:trouble_kill' row.id %}" class="btn btn-success btn-xs">
                                <i class="fa fa-pencil"></i>
                                处理订单
                            {% else %}
                                <a href="{% url 'backend:trouble_detail' row.id %}" class="btn btn-success btn-xs">
                                <i class="fa fa-pencil"></i>
                                解决方案
                                {% endif %}
                            </a>
                            {% if row.status == 2 %}
                            |
                            <a nid="{{ row.id }}" id="del-btn" ntitle="{{ row.title }}" class="btn btn-danger btn-xs">
                                    <i class="fa fa-times"></i> 取消订单
                            </a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="pager">
        <ul class="pagination">
            {{ page_str }}
        </ul>
    </div>

    <div class="modal fade" id="delModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="exampleModalLabel">删除报障单</h4>
                </div>
                <div class="modal-body">
{#                    确认删除分类: <span id="del-class-name" nid=""></span>？#}
                    <form>
                        <div class="form-group">
                            <label for="recipient-name" class="control-label">报障单标题</label>
                            <input type="text" class="form-control" id="del-class-name" value="" nid="" readonly>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">返回</button>
                    <button type="button" class="btn btn-danger" id="del-confirm">确认取消</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="/static/plugins/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
    <script>
        $(function () {
            bindDel();
            bindDelConfirm();
        });

        function bindDelConfirm() {
            $('#del-confirm').click(function () {
                var id = $('#del-class-name').attr('nid');
                //console.log(id);
                $.ajax({
                    url: '{% url "backend:trouble_kill_del" %}',
                    type: 'GET',
                    data: {'id': id},
                    dataType: 'JSON',
                    success: function (arg) {
                        //console.log(arg);
                        if (arg.status) {
                            //console.log($(this));
                            window.location.reload();
                            //$('#delModal').modal('hide');
                        }
                        else {
                            alert(arg.message);
                        }
                    }
                })
            })
        }


        function bindDel() {
            $('#tb').on('click', '#del-btn', function () {
                $('#delModal').modal('show');
                var name = $(this).attr('ntitle');
                var id = $(this).attr('nid');
                //console.log(name, id);
                $('#del-class-name').attr('nid', id);
                $('#del-class-name').val(name);
                //$('#del-class-name').text(name);
            })
        }
    </script>
{% endblock %}